### ISSUE TITLE
Introspection schema returns empty values for input types

### ISSUE THREAD

**Issue by danielvladco** [nautilus/graphql#4]
main.go:
```go
schemas, err := graphql.IntrospectRemoteSchemas(
		"http://localhost:3004/query",
		"http://localhost:3002/query",
		"http://localhost:3006/query",
	)
	if err != nil {
		panic(err)
	}

	// create the gateway instance
	gw, err := gateway.New(schemas)
	if err != nil {
		panic(err)
	}
	http.HandleFunc("/graphql", gw.PlaygroundHandler)
```
gql schema: 
```graphqls
# ... Service A
input ChangeCompanyInfoReqInput {
	company: CompanyInput  
}

# ... Service B
input DeleteSkillReqInput {
	id: String  
}

# ...
```
gql query:
"Introspection Query"

expected result:
The complete json representation of gql scheam

got:
```json
"types": [
        {
          "description": "",
          "enumValues": [],
          "fields": [],
          "inputFields": [],
          "interfaces": [],
          "kind": "",
          "name": "ChangeCompanyInfoReqInput",
          "possibleTypes": []
        },
        {
          "description": "",
          "enumValues": [],
          "fields": [],
          "inputFields": [],
          "interfaces": [],
          "kind": "",
          "name": "DeleteSkillReqInput",
          "possibleTypes": []
        },
]
```

all Input types are like this.

**Comment by AlecAivazis** [comment]
Okay so I've tried to see if I can reproduce your problem and I think I need a bit more information.

I ran the following code in a script and was able to find the fields for an input type:

```'
// introspect the apis
schemas, err := graphql.IntrospectRemoteSchemas(
	"https://api.graphql.jobs/",
)
if err != nil {
	panic(err)
}

fmt.Println(schemas[0].Schema.Types["TagWhereInput"].Fields)
```

Is the payload you posted above a response from introspecting the gateway? Or is that the introspection query to one of the backend services?

**Comment by danielvladco** [comment]
Hi @AlecAivazis ,
Thanks for quick reply,

run this piece of code:
```go
schemas, err := graphql.IntrospectRemoteSchemas(
	"https://api.graphql.jobs/",
)
if err != nil {
	panic(err)
}

, _ := json.Marshal(schemas[0].Schema.Types["TagWhereInput"])
fmt.Printf("%s/n", string(b))
```
notice how `Kind` field for input type is empty, when it's expected to be `INPUT_OBJECT`
also there are Fields but for some reason all their fields are resolved to zero values except for field `Name` and `Type` 

You can introspect the endpoint directly and see all the mismatching fields.

**Comment by AlecAivazis** [comment]
Ah yea I noticed a similar inconsistency today while digging through this. I'll try to have a fix for you very soon. Sorry about this!

**Comment by AlecAivazis** [comment]
Okay i just pushed a fix that assigns the right `Kind` to input objects. I tested the script again and am able to interact with the API through the playground provided by the gateway. 

Looking at the introspection query used in the gateway (the same used by most libraries) we only ask for `name`, `description`, `defaultValue`, and `type` information on input objects. What more would you like to see?

**Comment by AlecAivazis** [comment]
@danielvladco are you still seeing issues?

**Comment by danielvladco** [comment]
@AlecAivazis Unfortunately not, 

I use Insomnia as my graphql client and when it's trying to do introspection query I reveive this error:
![image](https://user-images.githubusercontent.com/22772954/61434642-29278380-a93f-11e9-9625-e153c35601b8.png)

When I use direct link however It works fine

**Comment by AlecAivazis** [comment]
Okay that’s progress! Looks like insomnia is expecting a directive to be defined that isn’t. I’ll go download it and give it a try

**Comment by AlecAivazis** [comment]
Alright I think we're in business now. I was able to reproduce your issue in `insomnia`. There was an error when pulling in the locations for directives. It should be fixed now in `v0.0.8`. Sorry for the inconvenience!

**Comment by danielvladco** [comment]
Thanks, It seems to work now

You forgot a print here https://github.com/nautilus/graphql/blob/master/introspection.go#L196
:)

**Comment by AlecAivazis** [comment]
Whoops! Thanks for catching that

**Comment by sbilello** [comment]
@danielvladco @AlecAivazis 
In a real production ready example, there is no schema registry involved with nautilus?
"http://localhost:3004/query",
"http://localhost:3002/query",
"http://localhost:3006/query",
How do you dynamically update the service list?
